import joblib
from fastapi import FastAPI
from pydantic import BaseModel
from ml.preprocess import clean_text

app = FastAPI()

# Load the trained model 
# generated by running ml/train/main.py and saved to outputs/
model = joblib.load("outputs/model.pkl")
vectorizer = joblib.load("outputs/vectorizer.pkl")

# Shape of the request body expected by the /predict endpoint
class PredictRequest(BaseModel):
    text: str

@app.post("/predict")
def predict(req: PredictRequest):
    # Clean the input text using the same preprocessing used during training
    clean = clean_text(req.text)

    # Convert text to a TF-IDF vector (same vectorizer fitted during training)
    vec = vectorizer.transform([clean])

    pred = model.predict(vec)[0]

    # predict_proba returns probabilities
    confidence = float(model.predict_proba(vec).max())

    label = "REAL" if pred == 1 else "FAKE"
    return {"label": label, "confidence": confidence}
